enum PermissionEnum {
  CREATE_COURSE = "CREATE_COURSE",
  EDIT_COURSE = "EDIT_COURSE",
  DELETE_COURSE = "DELETE_COURSE",
  VIEW_GRADES = "VIEW_GRADES",
  SUBMIT_ASSIGNMENT = "SUBMIT_ASSIGNMENT",
  MANAGE_USERS = "MANAGE_USERS", 
  VIEW_COURSE = "VIEW_COURSE"
}
export default PermissionEnum;